// featureDocSections.test.ts — The nine-section canon: constants, normalization, placeholders,
// AI-attribution stripping, and risk-key extraction (spec 029, contract document-structure.md).

import { describe, expect, it } from 'vitest';

import {
  buildValidationPlaceholder,
  DEFAULT_VALIDATION_KIND,
  extractRiskLinkKeys,
  normalizeFeatureDescription,
  SECTION_LABELS,
  stripAiAttribution,
  VALIDATION_MARKER,
} from './featureDocSections.ts';

describe('canon (Foundational)', () => {
  it('lists the nine section labels in the required order', () => {
    expect(SECTION_LABELS).toEqual([
      'Description', 'Benefit Hypothesis', 'Acceptance Criteria', 'Assumptions',
      'Dependencies', 'In Scope', 'Out of Scope', 'Risks', 'Non-Functional Requirements (NFR)',
    ]);
  });

  it('defines the three validation markers and a default kind per label', () => {
    expect(VALIDATION_MARKER.business).toBe('⚠ REQUIRES BUSINESS VALIDATION');
    expect(VALIDATION_MARKER.technical).toBe('⚠ REQUIRES TECHNICAL VALIDATION');
    expect(VALIDATION_MARKER.both).toBe('⚠ REQUIRES BUSINESS & TECHNICAL VALIDATION');
    expect(DEFAULT_VALIDATION_KIND['Benefit Hypothesis']).toBe('business');
    expect(DEFAULT_VALIDATION_KIND['Non-Functional Requirements (NFR)']).toBe('technical');
  });
});

describe('normalizeFeatureDescription (US1)', () => {
  it('emits all nine sections in order, preserving content and flagging missing ones', () => {
    const raw = [
      'Description: Users cannot reset their password.',
      'Benefit Hypothesis: Fewer support tickets.',
      'Risks: Depends on the email service ABC-123.',
    ].join('\n');
    const out = normalizeFeatureDescription(raw);

    // Order: the nine labels appear in canonical order.
    const positions = SECTION_LABELS.map((label) => out.indexOf(`${label}:`));
    expect(positions.every((position, index) => index === 0 || position > positions[index - 1])).toBe(true);

    expect(out).toContain('Description:\nUsers cannot reset their password.');
    expect(out).toContain('Benefit Hypothesis:\nFewer support tickets.');
    // A missing section (e.g. Assumptions) gets its default marker.
    expect(out).toContain(`Assumptions:\n${VALIDATION_MARKER.both}`);
    expect(out).toContain(`Dependencies:\n${VALIDATION_MARKER.technical}`);
  });

  it('is idempotent', () => {
    const raw = 'Description: A thing.\nRisks: none.';
    const once = normalizeFeatureDescription(raw);
    expect(normalizeFeatureDescription(once)).toBe(once);
  });

  it('folds preamble text before the first heading into Description', () => {
    const out = normalizeFeatureDescription('Some loose intro text.\nDescription: The real description.');
    expect(out).toContain('Some loose intro text.');
    expect(out.indexOf('Some loose intro text.')).toBeLessThan(out.indexOf('Benefit Hypothesis:'));
  });
});

describe('buildValidationPlaceholder (US1/US2)', () => {
  it('uses the label’s default marker and carries no AI attribution', () => {
    const placeholder = buildValidationPlaceholder('Risks');
    expect(placeholder).toContain(VALIDATION_MARKER.business);
    expect(placeholder.toLowerCase()).not.toMatch(/\bai\b|artificial intelligence/);
  });
});

describe('stripAiAttribution (US2)', () => {
  it('removes AI-authorship phrasing but keeps markers and normal prose', () => {
    const input = 'Description:\nThis description was generated by AI. Users cannot log in.\n⚠ REQUIRES BUSINESS VALIDATION';
    const out = stripAiAttribution(input);
    expect(out.toLowerCase()).not.toContain('generated by ai');
    expect(out).toContain('Users cannot log in.');
    expect(out).toContain('⚠ REQUIRES BUSINESS VALIDATION');
  });

  it('removes "as an AI language model" style phrasing', () => {
    const out = stripAiAttribution('As an AI language model, I suggest the following.');
    expect(out.toLowerCase()).not.toContain('as an ai');
  });
});

describe('extractRiskLinkKeys (US3)', () => {
  it('returns distinct Jira keys found only in the Risks section', () => {
    const description = normalizeFeatureDescription([
      'Description: Something about ABC-100.',
      'Dependencies: Needs DEF-200.',
      'Risks: Blocked by ABC-123 and also ABC-123 again, plus GHI-9.',
    ].join('\n'));
    expect(extractRiskLinkKeys(description)).toEqual(['ABC-123', 'GHI-9']); // ABC-100/DEF-200 excluded, ABC-123 de-duped
  });

  it('returns an empty list when the Risks section references no keys', () => {
    const description = normalizeFeatureDescription('Risks: No known blockers.');
    expect(extractRiskLinkKeys(description)).toEqual([]);
  });
});
