// bulkRewriteAiAssist.test.ts — Batch prompt (chunking) + keyed reply parse (spec 030, US1).

import { describe, expect, it } from 'vitest';

import { buildBulkRewritePrompts, parseBulkRewriteReply } from './bulkRewriteAiAssist.ts';
import type { CapturedOriginal } from '../rewriteBatchModel';
import type { ReferencedSource } from '../../sources/sourceModel.ts';

function original(overrides: Partial<CapturedOriginal> = {}): CapturedOriginal {
  return { summary: 'sum', description: 'desc', acceptanceCriteria: 'ac', capturedAtIso: '2026-07-26T00:00:00Z', ...overrides };
}

describe('buildBulkRewritePrompts', () => {
  it('produces one prompt for a small batch, carrying rules, markers, and the template', () => {
    const prompts = buildBulkRewritePrompts([
      { jiraKey: 'ABC-1', original: original() },
      { jiraKey: 'ABC-2', original: original() },
    ]);
    expect(prompts).toHaveLength(1);
    expect(prompts[0]).toContain('part 1 of 1');
    ['ABC-1', 'ABC-2', 'Non-Functional Requirements (NFR)', '⚠ REQUIRES BUSINESS VALIDATION', '"kind":"featureRewriteBatch"'].forEach((needle) => {
      expect(prompts[0]).toContain(needle);
    });
    expect(prompts[0].toLowerCase()).toContain('never state or imply');
  });

  it('splits a large batch across ordered prompts with every key present, none dropped', () => {
    const big = 'x'.repeat(4000);
    const items = Array.from({ length: 6 }, (_unused, index) => ({ jiraKey: `ABC-${index + 1}`, original: original({ description: big }) }));
    const prompts = buildBulkRewritePrompts(items);
    expect(prompts.length).toBeGreaterThan(1);
    expect(prompts[0]).toContain(`part 1 of ${prompts.length}`);
    const combined = prompts.join('\n');
    items.forEach((item) => expect(combined).toContain(item.jiraKey)); // no issue dropped
  });

  it('returns no prompts for an empty batch', () => {
    expect(buildBulkRewritePrompts([])).toEqual([]);
  });
});

describe('parseBulkRewriteReply', () => {
  const known = ['ABC-1', 'ABC-2'];

  it('maps keys to nine-section proposals; rejects unknown; counts missing; strips AI attribution', () => {
    const reply = JSON.stringify({
      kind: 'featureRewriteBatch',
      items: [
        { key: 'ABC-1', description: 'Description: This was generated by AI. Login broken.', acceptanceCriteria: 'AC1' },
        { key: 'NOPE-9', description: 'x' },              // unknown → rejected
        { key: 'ABC-2' },                                  // missing description → unparsed
      ],
    });
    const result = parseBulkRewriteReply(reply, known);
    expect(Object.keys(result.rewritesByKey)).toEqual(['ABC-1']);
    expect(result.rewritesByKey['ABC-1'].description).toContain('Benefit Hypothesis:'); // normalized to nine sections
    expect(result.rewritesByKey['ABC-1'].description.toLowerCase()).not.toContain('generated by ai');
    expect(result.rejected.map((r) => r.key)).toEqual(['NOPE-9']);
    expect(result.unparsedCount).toBe(1);
  });

  it('throws on wrong or missing kind', () => {
    expect(() => parseBulkRewriteReply(JSON.stringify({ kind: 'other', items: [] }), known)).toThrow(/featureRewriteBatch/);
    expect(() => parseBulkRewriteReply('no json', known)).toThrow();
  });

  it('multi-part replies merge by key (Object.assign of rewritesByKey)', () => {
    const part1 = parseBulkRewriteReply(JSON.stringify({ kind: 'featureRewriteBatch', items: [{ key: 'ABC-1', description: 'Description: one', acceptanceCriteria: 'a' }] }), known);
    const part2 = parseBulkRewriteReply(JSON.stringify({ kind: 'featureRewriteBatch', items: [{ key: 'ABC-2', description: 'Description: two', acceptanceCriteria: 'b' }] }), known);
    const merged = { ...part1.rewritesByKey, ...part2.rewritesByKey };
    expect(Object.keys(merged).sort()).toEqual(['ABC-1', 'ABC-2']);
  });
});

describe('buildBulkRewritePrompts with shared material', () => {
  function note(label: string, text: string): ReferencedSource {
    return { kind: 'paste', id: label, label, text };
  }

  it('carries the shared documents into the prompt', () => {
    const prompts = buildBulkRewritePrompts(
      [{ jiraKey: 'ABC-1', original: original() }],
      [note('Accessibility Standard', 'Contrast must be 4.5:1.')],
    );

    expect(prompts[0]).toContain('Accessibility Standard');
    expect(prompts[0]).toContain('Contrast must be 4.5:1.');
  });

  it('repeats the material in EVERY part, so a split batch is not re-written from nothing', () => {
    // The rule the whole feature rests on. Material carried only in part one would leave every
    // issue after the split re-written without the document that prompted the batch.
    const big = 'x'.repeat(4000);
    const items = Array.from({ length: 6 }, (_unused, index) => (
      { jiraKey: 'ABC-' + (index + 1), original: original({ description: big }) }
    ));

    const prompts = buildBulkRewritePrompts(items, [note('Standard', 'Contrast must be 4.5:1.')]);

    expect(prompts.length).toBeGreaterThan(1);
    prompts.forEach((prompt) => expect(prompt).toContain('Contrast must be 4.5:1.'));
  });

  it('still splits correctly once the material is taking up room', () => {
    // The material counts against the prompt budget. Ignoring it would build parts that overflow.
    const big = 'x'.repeat(4000);
    const items = Array.from({ length: 6 }, (_unused, index) => (
      { jiraKey: 'ABC-' + (index + 1), original: original({ description: big }) }
    ));

    const withMaterial = buildBulkRewritePrompts(items, [note('Standard', 'y'.repeat(5000))]);
    const combined = withMaterial.join(' ');
    items.forEach((item) => expect(combined).toContain(item.jiraKey));
  });

  it('is byte-identical to a plain batch when no material is supplied', () => {
    const items = [{ jiraKey: 'ABC-1', original: original() }];
    expect(buildBulkRewritePrompts(items, [])).toEqual(buildBulkRewritePrompts(items));
  });
});

describe('the enterprise Feature rules ride in every prompt', () => {
  it('tells the assistant that production is not delivery', () => {
    // Read from the shared gate module rather than restated here, so the prompt and the readiness
    // checks cannot drift into describing two different workflows.
    const prompts = buildBulkRewritePrompts([{ jiraKey: 'ABC-1', original: original() }]);
    expect(prompts[0]).toMatch(/Code in production is not delivery/i);
  });

  it('names the fields a Feature has to carry', () => {
    const prompts = buildBulkRewritePrompts([{ jiraKey: 'ABC-1', original: original() }]);
    expect(prompts[0]).toContain('Parent Link (Program Epic)');
    expect(prompts[0]).toContain('CMDB Application');
  });
});

describe('buildBulkRewritePrompts — a second pass adds to the first', () => {
  const original = {
    summary: 'Review the OEC file specs',
    description: 'A discovery feature for OEC file reviews.',
    acceptanceCriteria: 'Inventory reviewed.',
    capturedAtIso: '2026-08-21T00:00:00.000Z',
  };

  const working = {
    description: 'Description:\nReview all available OEC file specifications and layouts.',
    acceptanceCriteria: '- Inventory of OEC vendors and file sources reviewed.',
    isEdited: false,
  };

  it('sends the current draft as the working text, not just the original', () => {
    // Without this every re-run re-derived the nine sections from the original, and everything the
    // first pass got right had to be got right a second time by luck (GH #376).
    const [prompt] = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original, proposed: working }]);

    expect(prompt).toContain('WORKING DRAFT — extend this, do not start again');
    expect(prompt).toContain('Review all available OEC file specifications and layouts.');
  });

  it('still sends the original beside it, so nothing is derived from the draft alone', () => {
    const [prompt] = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original, proposed: working }]);

    expect(prompt).toContain('Original description:');
    expect(prompt).toContain('A discovery feature for OEC file reviews.');
  });

  it('tells the assistant that a SHORTER draft losing agreed detail is wrong', () => {
    const [prompt] = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original, proposed: working }]);

    expect(prompt).toContain('EXTEND it');
    expect(prompt).toContain('loses detail already agreed is wrong');
  });

  it('says nothing about a working draft on a first pass', () => {
    const [prompt] = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original, proposed: null }]);

    expect(prompt).not.toContain('WORKING DRAFT — extend this');
  });

  it('treats an empty draft as no draft rather than sending a blank section', () => {
    const emptyDraft = { description: '   ', acceptanceCriteria: '', isEdited: false };

    const [prompt] = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original, proposed: emptyDraft }]);

    expect(prompt).not.toContain('WORKING DRAFT — extend this');
  });

  it('builds the same prompt it always did for a caller that passes no proposal at all', () => {
    const withoutField = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original }]);
    const withNull = buildBulkRewritePrompts([{ jiraKey: 'DENP-1437', original, proposed: null }]);

    expect(withoutField).toEqual(withNull);
  });
});
