// bulkRewriteAiAssist.test.ts — Batch prompt (chunking) + keyed reply parse (spec 030, US1).

import { describe, expect, it } from 'vitest';

import { buildBulkRewritePrompts, parseBulkRewriteReply } from './bulkRewriteAiAssist.ts';
import type { CapturedOriginal } from '../rewriteBatchModel';

function original(overrides: Partial<CapturedOriginal> = {}): CapturedOriginal {
  return { summary: 'sum', description: 'desc', acceptanceCriteria: 'ac', capturedAtIso: '2026-07-26T00:00:00Z', ...overrides };
}

describe('buildBulkRewritePrompts', () => {
  it('produces one prompt for a small batch, carrying rules, markers, and the template', () => {
    const prompts = buildBulkRewritePrompts([
      { jiraKey: 'ABC-1', original: original() },
      { jiraKey: 'ABC-2', original: original() },
    ]);
    expect(prompts).toHaveLength(1);
    expect(prompts[0]).toContain('part 1 of 1');
    ['ABC-1', 'ABC-2', 'Non-Functional Requirements (NFR)', '⚠ REQUIRES BUSINESS VALIDATION', '"kind":"featureRewriteBatch"'].forEach((needle) => {
      expect(prompts[0]).toContain(needle);
    });
    expect(prompts[0].toLowerCase()).toContain('never state or imply');
  });

  it('splits a large batch across ordered prompts with every key present, none dropped', () => {
    const big = 'x'.repeat(4000);
    const items = Array.from({ length: 6 }, (_unused, index) => ({ jiraKey: `ABC-${index + 1}`, original: original({ description: big }) }));
    const prompts = buildBulkRewritePrompts(items);
    expect(prompts.length).toBeGreaterThan(1);
    expect(prompts[0]).toContain(`part 1 of ${prompts.length}`);
    const combined = prompts.join('\n');
    items.forEach((item) => expect(combined).toContain(item.jiraKey)); // no issue dropped
  });

  it('returns no prompts for an empty batch', () => {
    expect(buildBulkRewritePrompts([])).toEqual([]);
  });
});

describe('parseBulkRewriteReply', () => {
  const known = ['ABC-1', 'ABC-2'];

  it('maps keys to nine-section proposals; rejects unknown; counts missing; strips AI attribution', () => {
    const reply = JSON.stringify({
      kind: 'featureRewriteBatch',
      items: [
        { key: 'ABC-1', description: 'Description: This was generated by AI. Login broken.', acceptanceCriteria: 'AC1' },
        { key: 'NOPE-9', description: 'x' },              // unknown → rejected
        { key: 'ABC-2' },                                  // missing description → unparsed
      ],
    });
    const result = parseBulkRewriteReply(reply, known);
    expect(Object.keys(result.rewritesByKey)).toEqual(['ABC-1']);
    expect(result.rewritesByKey['ABC-1'].description).toContain('Benefit Hypothesis:'); // normalized to nine sections
    expect(result.rewritesByKey['ABC-1'].description.toLowerCase()).not.toContain('generated by ai');
    expect(result.rejected.map((r) => r.key)).toEqual(['NOPE-9']);
    expect(result.unparsedCount).toBe(1);
  });

  it('throws on wrong or missing kind', () => {
    expect(() => parseBulkRewriteReply(JSON.stringify({ kind: 'other', items: [] }), known)).toThrow(/featureRewriteBatch/);
    expect(() => parseBulkRewriteReply('no json', known)).toThrow();
  });

  it('multi-part replies merge by key (Object.assign of rewritesByKey)', () => {
    const part1 = parseBulkRewriteReply(JSON.stringify({ kind: 'featureRewriteBatch', items: [{ key: 'ABC-1', description: 'Description: one', acceptanceCriteria: 'a' }] }), known);
    const part2 = parseBulkRewriteReply(JSON.stringify({ kind: 'featureRewriteBatch', items: [{ key: 'ABC-2', description: 'Description: two', acceptanceCriteria: 'b' }] }), known);
    const merged = { ...part1.rewritesByKey, ...part2.rewritesByKey };
    expect(Object.keys(merged).sort()).toEqual(['ABC-1', 'ABC-2']);
  });
});
