#!/usr/bin/env pwsh
# Forge Workflow Pre-Push Hook
# Generated by Forge Terminal Workflow Architect
# Runs build + test suite before allowing push. Ensures broken code never reaches remote.
# Bypass with: git push --no-verify

$ErrorActionPreference = "Continue"
$failures = @()

Write-Host "Running pre-push checks..." -ForegroundColor Cyan

# ── Go Build + Test ─────────────────────────────────────────────────────
if (Test-Path "go.mod") {
    Write-Host "  [Go] Building..." -ForegroundColor Cyan
    $buildOutput = go build ./cmd/forge/ 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures += "GO BUILD: go build ./cmd/forge/ failed"
        Write-Host "  [Go] Build FAILED" -ForegroundColor Red
        Write-Host $buildOutput -ForegroundColor Red
    } else {
        Write-Host "  [Go] Build passed" -ForegroundColor Green
    }

    Write-Host "  [Go] Testing..." -ForegroundColor Cyan
    $testOutput = go test ./... 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures += "GO TEST: go test ./... failed"
        Write-Host "  [Go] Tests FAILED" -ForegroundColor Red
        Write-Host $testOutput -ForegroundColor Red
    } else {
        Write-Host "  [Go] Tests passed" -ForegroundColor Green
    }
}

# ── Frontend Build + Test ───────────────────────────────────────────────
if (Test-Path "frontend/package.json") {
    Write-Host "  [Frontend] Testing..." -ForegroundColor Cyan
    Push-Location frontend
    $vitestOutput = npx vitest run 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures += "FRONTEND TEST: npx vitest run failed"
        Write-Host "  [Frontend] Tests FAILED" -ForegroundColor Red
        Write-Host $vitestOutput -ForegroundColor Red
    } else {
        Write-Host "  [Frontend] Tests passed" -ForegroundColor Green
    }
    Pop-Location
}

# ── Client (React SPA) Typecheck ────────────────────────────────────────
# This repo's SPA lives in client/ (not frontend/). Run the SAME project build the
# release uses — `tsc -b` — so a type error that `tsc --noEmit` or `vite build` tolerate
# (e.g. a missing type import) is caught here, before it can reach main and break a release.
#
# Skip cache: a release pushes several times in a row (main, tag, branch cleanup) with an
# identical working tree, and re-typechecking the same code adds minutes for zero safety.
# The git tree hash of client/ identifies its exact committed content, so when the working
# tree is clean and that same hash already passed a typecheck, this run is skipped.
if (Test-Path "client/package.json") {
    $typecheckCacheFile = ".forge/cache/pre-push-client-tree"
    $clientTreeHash     = git rev-parse "HEAD:client" 2>$null
    $clientDirtyFiles   = git status --porcelain -- client 2>$null
    $hasVerifiedTree    = $clientTreeHash -and (-not $clientDirtyFiles) -and (Test-Path $typecheckCacheFile) -and ((Get-Content $typecheckCacheFile -Raw).Trim() -eq $clientTreeHash)

    if ($hasVerifiedTree) {
        Write-Host "  [Client] Typecheck skipped — client/ tree already verified ($($clientTreeHash.Substring(0, 12)))" -ForegroundColor Green
    } else {
        Write-Host "  [Client] Typechecking (tsc -b)..." -ForegroundColor Cyan
        Push-Location client
        $typecheckOutput = npx tsc -b 2>&1
        $typecheckExit = $LASTEXITCODE
        Pop-Location
        if ($typecheckExit -ne 0) {
            $failures += "CLIENT TYPECHECK: npx tsc -b failed"
            Write-Host "  [Client] Typecheck FAILED" -ForegroundColor Red
            Write-Host $typecheckOutput -ForegroundColor Red
        } else {
            Write-Host "  [Client] Typecheck passed" -ForegroundColor Green
            # Only a clean tree can be trusted for future skips — uncommitted client/
            # edits were typechecked here but are not represented by the tree hash.
            if ($clientTreeHash -and (-not $clientDirtyFiles)) {
                New-Item -ItemType Directory -Path ".forge/cache" -Force | Out-Null
                Set-Content -Path $typecheckCacheFile -Value $clientTreeHash -Encoding ASCII
            }
        }
    }
}

# ── Report ──────────────────────────────────────────────────────────────
if ($failures.Count -gt 0) {
    Write-Host ""
    Write-Host "PRE-PUSH FAILURES (blocking):" -ForegroundColor Red
    foreach ($f in $failures) { Write-Host "  * $f" -ForegroundColor Red }
    Write-Host "Push blocked. Fix failures or use --no-verify to bypass." -ForegroundColor Red
    exit 1
}

Write-Host "Pre-push checks passed" -ForegroundColor Green
exit 0
