// intakeDraftRound.test.ts — Contract tests for the Epic draft shape (spec 037, contracts/ai-rounds.md §3):
// nine-section normalisation, the Shared-scope suffix, and the manual draft.

import { describe, expect, it } from 'vitest';

import { SECTION_LABELS } from '../../ai/featureDocSections.ts';
import { createIntakeItem, type Decision, type EpicDraft, type IntakeItem, type SourceLine } from '../epicIntakeModel.ts';
import {
  applySharedScopeSuffix,
  buildManualDraft,
  isSharedItem,
  MAX_EPIC_SUMMARY_CHARS,
  readDraftFromReply,
  SHARED_SCOPE_SUFFIX,
} from './intakeDraftRound.ts';

function settled<TValue>(value: TValue): Decision<TValue> {
  return { state: 'settled', value, settledBy: 'rule', reason: 'test', aiAttempts: 0 };
}

const LINES: SourceLine[] = [
  { lineNumber: 1, text: 'Invoice overhaul', rawText: '•\tInvoice overhaul', outlineLevel: 1 },
  { lineNumber: 2, text: 'Analysis', rawText: 'o\tAnalysis', outlineLevel: 2 },
];

function buildItem(title: string, owner: 'enrollment' | 'shared'): IntakeItem {
  const item = createIntakeItem(1, title, [1, 2]);
  item.decisions.owner = settled(owner);
  return item;
}

describe('readDraftFromReply', () => {
  it('normalises the description to nine sections and strips authorship claims', () => {
    const draft = readDraftFromReply({ summary: 'Invoice overhaul', description: 'Description:\nRedo invoices. This was generated by AI.' }) as EpicDraft;
    expect(draft).toMatchObject({ summary: 'Invoice overhaul', source: 'ai', editedByPo: false });
    expect(draft.description).toContain('Redo invoices.');
    expect(draft.description).not.toMatch(/generated by AI/i);
    expect(SECTION_LABELS.every((label) => draft.description.includes(`${label}:`))).toBe(true);
  });

  it('refuses an over-long summary or an empty description', () => {
    expect(readDraftFromReply({ summary: 'x'.repeat(MAX_EPIC_SUMMARY_CHARS + 1), description: 'd' })).toMatch(/summary/);
    expect(readDraftFromReply({ summary: 's', description: '  ' })).toMatch(/description/);
  });
});

describe('buildManualDraft', () => {
  it('uses the title and the item\'s lines, flagging the other eight sections', () => {
    const draft = buildManualDraft(buildItem('Invoice overhaul', 'enrollment'), LINES);
    expect(draft.summary).toBe('Invoice overhaul');
    expect(draft.description).toContain('- Analysis');
    expect(draft.description).toContain('⚠ REQUIRES');
    expect(draft.source).toBe('po');
  });
});

describe('Shared items — an Epic for Enrollment\'s part only', () => {
  it('recognises a Shared item', () => {
    expect(isSharedItem(buildItem('AEP', 'shared'))).toBe(true);
    expect(isSharedItem(buildItem('AEP', 'enrollment'))).toBe(false);
  });

  it('adds the suffix to the manual draft and keeps it within Jira\'s summary limit', () => {
    expect(buildManualDraft(buildItem('AEP', 'shared'), LINES).summary).toBe(`AEP${SHARED_SCOPE_SUFFIX}`);
    expect(applySharedScopeSuffix('x'.repeat(MAX_EPIC_SUMMARY_CHARS), true)).toHaveLength(MAX_EPIC_SUMMARY_CHARS);
    expect(applySharedScopeSuffix(`AEP${SHARED_SCOPE_SUFFIX}`, true)).toBe(`AEP${SHARED_SCOPE_SUFFIX}`);
    expect(applySharedScopeSuffix('Plain', false)).toBe('Plain');
  });
});
