// intakeDraftRound.test.ts — Contract tests for the drafting exchange (spec 037, contracts/ai-rounds.md §3):
// own-lines-only prompts, nine-section normalisation, PO edits protected, and the manual draft.

import { describe, expect, it } from 'vitest';

import { SECTION_LABELS } from '../../ai/featureDocSections.ts';
import {
  createIntakeItem,
  EPIC_INTAKE_SCHEMA_VERSION,
  type Decision,
  type EpicIntake,
  type IntakeItem,
  type SourceLine,
} from '../epicIntakeModel.ts';
import { listOpenDecisions } from '../intakeChecklist.ts';
import {
  applyDraftOutcome,
  buildDraftRequest,
  buildManualDraft,
  DRAFT_REPLY_KIND,
  MAX_EPIC_SUMMARY_CHARS,
  parseDraftReply,
} from './intakeDraftRound.ts';

const NOW_ISO = '2026-09-18T12:00:00.000Z';

function settled<TValue>(value: TValue, settledBy: 'rule' | 'ai' | 'po' = 'rule'): Decision<TValue> {
  return { state: 'settled', value, settledBy, reason: 'test', aiAttempts: 0 };
}

const LINES: SourceLine[] = [
  { lineNumber: 1, text: 'Invoice overhaul', rawText: '•\tInvoice overhaul', outlineLevel: 1 },
  { lineNumber: 2, text: 'Analysis', rawText: 'o\tAnalysis', outlineLevel: 2 },
  { lineNumber: 3, text: 'Paperless Options', rawText: '•\tPaperless Options', outlineLevel: 1 },
];

function buildNewEpicItem(itemNumber: number, title: string, lineNumbers: number[]): IntakeItem {
  const item = createIntakeItem(itemNumber, title, lineNumbers);
  item.decisions.kind = settled('work');
  item.decisions.owner = settled('enrollment');
  item.decisions.searchTerms = settled(['x']);
  item.searchStatus = 'ok';
  item.decisions.duplicate = settled({ verdict: 'createNew' });
  item.decisions.label = settled('Roadmap', 'po');
  return item;
}

function buildIntake(items: IntakeItem[]): EpicIntake {
  return {
    schemaVersion: EPIC_INTAKE_SCHEMA_VERSION, id: 'i', teamProfileId: 't', name: 'n', targetProjectKey: 'DENP',
    createdAtIso: NOW_ISO, updatedAtIso: NOW_ISO, sourceTitles: [], lines: LINES, items, setAsideLines: [],
    epicType: { state: 'resolved', id: '1', name: 'Epic' }, batchRequiredFieldValues: {}, roundHistory: [],
  };
}

function reply(items: unknown[]): string {
  return JSON.stringify({ kind: DRAFT_REPLY_KIND, items });
}

describe('buildDraftRequest', () => {
  it('asks only for new Epics without a draft, quoting each item\'s own lines and all nine sections', () => {
    const drafted = buildNewEpicItem(2, 'Paperless Options', [3]);
    drafted.draft = { summary: 'x', description: 'y', source: 'ai', editedByPo: false };
    const request = buildDraftRequest(buildIntake([buildNewEpicItem(1, 'Invoice overhaul', [1, 2]), drafted]));
    expect(request.itemIds).toEqual(['item-1']);
    expect(request.text).toContain('o\tAnalysis');
    expect(request.text).not.toContain('Paperless Options');
    for (const label of SECTION_LABELS) {
      expect(request.text).toContain(`- ${label}`);
    }
    expect(request.text).toContain('label: Roadmap');
  });
});

describe('parseDraftReply', () => {
  it('normalises the description to nine sections and strips authorship claims', () => {
    const outcome = parseDraftReply(reply([{ id: 'item-1', summary: 'Invoice overhaul', description: 'Description:\nRedo invoices. This was generated by AI.' }]), ['item-1']);
    const { description } = outcome.accepted[0].draft;
    expect(description).toContain('Redo invoices.');
    expect(description).not.toMatch(/generated by AI/i);
    expect(SECTION_LABELS.every((label) => description.includes(`${label}:`))).toBe(true);
  });

  it('rejects an over-long summary and an item that was not asked about', () => {
    const outcome = parseDraftReply(reply([
      { id: 'item-1', summary: 'x'.repeat(MAX_EPIC_SUMMARY_CHARS + 1), description: 'd' },
      { id: 'item-7', summary: 's', description: 'd' },
    ]), ['item-1']);
    expect(outcome.accepted).toEqual([]);
    expect(outcome.rejected.map((rejection) => rejection.itemId)).toEqual(['item-1', 'item-7']);
  });
});

describe('applyDraftOutcome', () => {
  it('stores the draft so the PO is asked to accept it', () => {
    const intake = buildIntake([buildNewEpicItem(1, 'Invoice overhaul', [1, 2])]);
    const applied = applyDraftOutcome(intake, parseDraftReply(reply([{ id: 'item-1', summary: 'S', description: 'D' }]), ['item-1']), ['item-1'], NOW_ISO);
    expect(applied.items[0].draft).toMatchObject({ summary: 'S', source: 'ai', editedByPo: false });
    expect(listOpenDecisions(applied, true).find((openDecision) => openDecision.slot === 'draftAccepted')?.turn).toBe('po');
  });

  it('never replaces a draft the PO has edited', () => {
    const item = buildNewEpicItem(1, 'Invoice overhaul', [1, 2]);
    item.draft = { summary: 'Mine', description: 'Mine', source: 'ai', editedByPo: true };
    const applied = applyDraftOutcome(buildIntake([item]), parseDraftReply(reply([{ id: 'item-1', summary: 'S', description: 'D' }]), ['item-1']), ['item-1'], NOW_ISO);
    expect(applied.items[0].draft?.summary).toBe('Mine');
  });

  it('counts a missing draft as an attempt', () => {
    const intake = buildIntake([buildNewEpicItem(1, 'Invoice overhaul', [1, 2])]);
    const applied = applyDraftOutcome(intake, parseDraftReply(reply([]), ['item-1']), ['item-1'], NOW_ISO);
    expect(applied.items[0].decisions.draftAccepted).toMatchObject({ state: 'open', aiAttempts: 1 });
  });
});

describe('buildManualDraft', () => {
  it('uses the title and the item\'s lines, flagging the other eight sections', () => {
    const draft = buildManualDraft(buildNewEpicItem(1, 'Invoice overhaul', [1, 2]), LINES);
    expect(draft.summary).toBe('Invoice overhaul');
    expect(draft.description).toContain('- Analysis');
    expect(draft.description).toContain('⚠ REQUIRES');
    expect(draft.source).toBe('po');
  });
});
