// rewriteBatchExport.test.ts — Before/after Markdown + self-contained HTML (spec 030, US3).

import { describe, expect, it } from 'vitest';

import { buildHtmlExport, buildMarkdownExport } from './rewriteBatchExport.ts';
import type { BatchExportInput } from './rewriteBatchModel';

const items: BatchExportInput[] = [
  {
    jiraKey: 'ABC-1',
    original: { summary: 'Old login', description: 'old desc', acceptanceCriteria: 'old ac', capturedAtIso: '2026-07-26T00:00:00Z' },
    proposed: { description: 'Description:\nnew desc', acceptanceCriteria: 'new ac', isEdited: false },
  },
];

describe('buildMarkdownExport', () => {
  it('pairs each issue key with Before and After', () => {
    const md = buildMarkdownExport(items);
    expect(md).toContain('## ABC-1');
    expect(md).toContain('### Before');
    expect(md).toContain('old desc');
    expect(md).toContain('### After (proposed description + acceptance criteria)');
    expect(md).toContain('new desc');
  });

  it('handles an empty batch', () => {
    expect(buildMarkdownExport([])).toContain('before / after');
  });
});

describe('buildHtmlExport', () => {
  it('is self-contained (no external assets) and shows each issue before + after', () => {
    const html = buildHtmlExport(items);
    expect(html.startsWith('<!doctype html>')).toBe(true);
    expect(html).toContain('ABC-1');
    expect(html).toContain('old desc');
    expect(html).toContain('new desc');
    // No external stylesheet/script/image references.
    expect(html).not.toMatch(/(src|href)\s*=\s*["']https?:/i);
    expect(html).not.toMatch(/<script/i);
  });

  it('escapes HTML in issue content', () => {
    const html = buildHtmlExport([{ ...items[0], original: { ...items[0].original, summary: '<b>x</b>' } }]);
    expect(html).toContain('&lt;b&gt;x&lt;/b&gt;');
  });
});

describe('no AI attribution', () => {
  it('neither export mentions AI authorship', () => {
    expect(buildMarkdownExport(items).toLowerCase()).not.toMatch(/generated by ai|written by ai|drafted by ai/);
    expect(buildHtmlExport(items).toLowerCase()).not.toMatch(/generated by ai|written by ai|drafted by ai/);
  });
});
